use crate::common::{test_part_one_common, test_part_two_common};
use crate::day08::Day08;

static INPUT_EXAMPLE: &str = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
";

#[test]
fn test_part_one() {
    test_part_one_common(Day08::default(), INPUT_EXAMPLE, 14);
}

#[test]
fn test_part_two() {
    test_part_two_common(Day08::default(), INPUT_EXAMPLE, 34);
}
